name: CI/CD Angular

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '15.12.0' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - run: npm install
      - run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: scratchunderflow
          path: ./dist
  deploy_andy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download builded app
      - uses: actions/checkout@v2
      - name: Download builded app
      - uses: actions/download-artifact@v2
        with:
          name: scratchunderflow
          path: distfiles
      - name: Display structure of downloaded files
      - run: ls .
      - uses: actions/checkout@v1
      - name: Copy repository contents via scp
      - uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.REMOTE_HOST1 }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: distfiles/*
          target: "."
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST1 }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: touch test.txt
  deploy_breval:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download builded app
      - uses: actions/checkout@v2
      - name: Download builded app
      - uses: actions/download-artifact@v2
        with:
          name: scratchunderflow
          path: distfiles
      - name: Display structure of downloaded files
      - run: ls .
      - uses: actions/checkout@v1
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.REMOTE_HOST2 }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: distfiles/*
          target: "."
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST1 }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: touch test.txt
#          script: cd bot && echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} > .env.example && echo OWNER_ID=${{ secrets.OWNER_ID }} >> .env.example && echo URL_EDT="https://api-calendar.calendz.app/v1/" >> .env.example && mv .env.example .env && chmod +x setup.sh && sudo systemctl restart bot.service
