name: CI/CD Python

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

jobs:
  npm:
    runs-on: ubuntu-lasted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install NPM packages
      - run: npm install
      - name: Build angular app
      - run: npm run build
  deploy1:
    needs: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.REMOTE_HOST1 }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "."
          target: .

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST1 }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: touch test.txt
#           script: cd bot && echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} > .env.example && echo OWNER_ID=${{ secrets.OWNER_ID }} >> .env.example && echo URL_EDT="https://api-calendar.calendz.app/v1/" >> .env.example && mv .env.example .env && chmod +x setup.sh && sudo systemctl restart bot.service
