name: CI/CD Angular

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '15.12.0' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - run: npm install
      - run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: scratchunderflow
          path: ./dist/scratchunderflow/*
  deploy_breval:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: MKDIR dir 
        run: mkdir dist
      - run: mkdir dist/scratchunderflow
      - name: Download builded app
        uses: actions/download-artifact@v2
        with:
          name: scratchunderflow
          path: dist/scratchunderflow/
      - name: Display structure of downloaded files
        run: ls -R .
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: dist/scratchunderflow/
          target: .
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sudo bash setup-cicd.sh
